package net.stylesolo.www.vo;

import java.sql.Date;

public class ShopCancelListVo {
	private int SHOP_PAYMENT_ITEM_NUM;
	private int SHOP_PAYMENT_ORDERNUM;
	private Date SHOP_PAYMENT_W_DATE;
	private Date CANCEL_APPLYDATE;
	private String SHOP_ITEM_NAME;
	private int SHOP_PAYMENT_ITEM_ORDER_QTY;
	private int SHOP_PAYMENT_ITEM_PRICE;
	private String CANCEL_HISTORY;
	private String ITEM_OPTIONS_NAME;
	public ShopCancelListVo(){}
	
	public ShopCancelListVo(int sHOP_PAYMENT_ITEM_NUM, int sHOP_PAYMENT_ORDERNUM, Date sHOP_PAYMENT_W_DATE,
			Date cANCEL_APPLYDATE, String sHOP_ITEM_NAME, int sHOP_PAYMENT_ITEM_ORDER_QTY, int sHOP_PAYMENT_ITEM_PRICE,
			String cANCEL_HISTORY, String iTEM_OPTIONS_NAME) {
		super();
		SHOP_PAYMENT_ITEM_NUM = sHOP_PAYMENT_ITEM_NUM;
		SHOP_PAYMENT_ORDERNUM = sHOP_PAYMENT_ORDERNUM;
		SHOP_PAYMENT_W_DATE = sHOP_PAYMENT_W_DATE;
		CANCEL_APPLYDATE = cANCEL_APPLYDATE;
		SHOP_ITEM_NAME = sHOP_ITEM_NAME;
		SHOP_PAYMENT_ITEM_ORDER_QTY = sHOP_PAYMENT_ITEM_ORDER_QTY;
		SHOP_PAYMENT_ITEM_PRICE = sHOP_PAYMENT_ITEM_PRICE;
		CANCEL_HISTORY = cANCEL_HISTORY;
		ITEM_OPTIONS_NAME = iTEM_OPTIONS_NAME;
	}

	
	public String getITEM_OPTIONS_NAME() {
		return ITEM_OPTIONS_NAME;
	}

	public void setITEM_OPTIONS_NAME(String iTEM_OPTIONS_NAME) {
		ITEM_OPTIONS_NAME = iTEM_OPTIONS_NAME;
	}

	public int getSHOP_PAYMENT_ITEM_NUM() {
		return SHOP_PAYMENT_ITEM_NUM;
	}
	public void setSHOP_PAYMENT_ITEM_NUM(int sHOP_PAYMENT_ITEM_NUM) {
		SHOP_PAYMENT_ITEM_NUM = sHOP_PAYMENT_ITEM_NUM;
	}
	public int getSHOP_PAYMENT_ORDERNUM() {
		return SHOP_PAYMENT_ORDERNUM;
	}
	public void setSHOP_PAYMENT_ORDERNUM(int sHOP_PAYMENT_ORDERNUM) {
		SHOP_PAYMENT_ORDERNUM = sHOP_PAYMENT_ORDERNUM;
	}
	public Date getSHOP_PAYMENT_W_DATE() {
		return SHOP_PAYMENT_W_DATE;
	}
	public void setSHOP_PAYMENT_W_DATE(Date sHOP_PAYMENT_W_DATE) {
		SHOP_PAYMENT_W_DATE = sHOP_PAYMENT_W_DATE;
	}
	public Date getCANCEL_APPLYDATE() {
		return CANCEL_APPLYDATE;
	}
	public void setCANCEL_APPLYDATE(Date cANCEL_APPLYDATE) {
		CANCEL_APPLYDATE = cANCEL_APPLYDATE;
	}
	public String getSHOP_ITEM_NAME() {
		return SHOP_ITEM_NAME;
	}
	public void setSHOP_ITEM_NAME(String sHOP_ITEM_NAME) {
		SHOP_ITEM_NAME = sHOP_ITEM_NAME;
	}
	public int getSHOP_PAYMENT_ITEM_ORDER_QTY() {
		return SHOP_PAYMENT_ITEM_ORDER_QTY;
	}
	public void setSHOP_PAYMENT_ITEM_ORDER_QTY(int sHOP_PAYMENT_ITEM_ORDER_QTY) {
		SHOP_PAYMENT_ITEM_ORDER_QTY = sHOP_PAYMENT_ITEM_ORDER_QTY;
	}
	public int getSHOP_PAYMENT_ITEM_PRICE() {
		return SHOP_PAYMENT_ITEM_PRICE;
	}
	public void setSHOP_PAYMENT_ITEM_PRICE(int sHOP_PAYMENT_ITEM_PRICE) {
		SHOP_PAYMENT_ITEM_PRICE = sHOP_PAYMENT_ITEM_PRICE;
	}
	public String getCANCEL_HISTORY() {
		return CANCEL_HISTORY;
	}
	public void setCANCEL_HISTORY(String cANCEL_HISTORY) {
		CANCEL_HISTORY = cANCEL_HISTORY;
	}
	
}
