package net.stylesolo.www.vo;

/**
 * 찜테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TbItemsetJjimVo{
	/** 글번호. */
	private int itemset_jjim_num;

	/** 회원아이디. */
	private String member_privacy_id;

	/** 추천 코드 테이블. */
	private int item_code_num;

	/**
	 * 생성자.
	 */
	public TbItemsetJjimVo() {
	}

	public TbItemsetJjimVo(int itemset_jjim_num, String member_privacy_id, int item_code_num) {
		super();
		this.itemset_jjim_num = itemset_jjim_num;
		this.member_privacy_id = member_privacy_id;
		this.item_code_num = item_code_num;
	}

	public int getItemset_jjim_num() {
		return itemset_jjim_num;
	}

	public void setItemset_jjim_num(int itemset_jjim_num) {
		this.itemset_jjim_num = itemset_jjim_num;
	}

	public String getMember_privacy_id() {
		return member_privacy_id;
	}

	public void setMember_privacy_id(String member_privacy_id) {
		this.member_privacy_id = member_privacy_id;
	}

	public int getItem_code_num() {
		return item_code_num;
	}

	public void setItem_code_num(int item_code_num) {
		this.item_code_num = item_code_num;
	}

}
