package net.stylesolo.www.vo;

/**
 * 세트_장바구니테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TbItemsetCartVo{

	private int itemset_cart_num;

	/** 회원아이디. */
	private String member_privacy_id;

	/** 주문수량. */
	private int itemset_cart_order_qty;

	/** 금액. */
	private int itemset_cart_price;

	/** 추천 코드 테이블. */
	private int itemset_code_num;

	/**
	 * 생성자.
	 */
	public TbItemsetCartVo() {
	
	}

	public TbItemsetCartVo(int itemset_cart_num, String member_privacy_id, int itemset_cart_order_qty,
			int itemset_cart_price, int itemset_code_num) {
		super();
		this.itemset_cart_num = itemset_cart_num;
		this.member_privacy_id = member_privacy_id;
		this.itemset_cart_order_qty = itemset_cart_order_qty;
		this.itemset_cart_price = itemset_cart_price;
		this.itemset_code_num = itemset_code_num;
	}

	public int getItemset_cart_num() {
		return itemset_cart_num;
	}

	public void setItemset_cart_num(int itemset_cart_num) {
		this.itemset_cart_num = itemset_cart_num;
	}

	public String getMember_privacy_id() {
		return member_privacy_id;
	}

	public void setMember_privacy_id(String member_privacy_id) {
		this.member_privacy_id = member_privacy_id;
	}

	public int getItemset_cart_order_qty() {
		return itemset_cart_order_qty;
	}

	public void setItemset_cart_order_qty(int itemset_cart_order_qty) {
		this.itemset_cart_order_qty = itemset_cart_order_qty;
	}

	public int getItemset_cart_price() {
		return itemset_cart_price;
	}

	public void setItemset_cart_price(int itemset_cart_price) {
		this.itemset_cart_price = itemset_cart_price;
	}

	public int getItemset_code_num() {
		return itemset_code_num;
	}

	public void setItemset_code_num(int itemset_code_num) {
		this.itemset_code_num = itemset_code_num;
	}
	
}
