package net.stylesolo.www.vo;

/**
 * MD추천메인상품 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TbItemsetMdrecVo {
	private int mdrec_num;

	/** 추천 코드 테이블. */
	private int item_code_num;

	/** MD추천 상품설명. */
	private String mdrec_ptation;
	private String itemset_code_mainimg;
	
	
	/**
	 * 생성자.
	 */
	public TbItemsetMdrecVo() {
		
	}


	public TbItemsetMdrecVo(int mdrec_num, int item_code_num, String mdrec_ptation, String itemset_code_mainimg) {
		super();
		this.mdrec_num = mdrec_num;
		this.item_code_num = item_code_num;
		this.mdrec_ptation = mdrec_ptation;
		this.itemset_code_mainimg = itemset_code_mainimg;
	}


	public int getMdrec_num() {
		return mdrec_num;
	}


	public void setMdrec_num(int mdrec_num) {
		this.mdrec_num = mdrec_num;
	}


	public int getItem_code_num() {
		return item_code_num;
	}


	public void setItem_code_num(int item_code_num) {
		this.item_code_num = item_code_num;
	}


	public String getMdrec_ptation() {
		return mdrec_ptation;
	}


	public void setMdrec_ptation(String mdrec_ptation) {
		this.mdrec_ptation = mdrec_ptation;
	}


	public String getItemset_code_mainimg() {
		return itemset_code_mainimg;
	}


	public void setItemset_code_mainimg(String itemset_code_mainimg) {
		this.itemset_code_mainimg = itemset_code_mainimg;
	}
	
}