package net.stylesolo.www.vo;
import java.sql.Date;


/**
 * 추천 코드 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TbItemsetCodeVo{
	/** 추천 코드 번호. */
	private int item_code_num;

	/** 추천 카테고리. */
	private String itemset_code_category;

	/** 추천 세트명. */
	private String item_code_setname;

	/** 세트 제품 가격. */
	private int itemset_code_price;

	/** 세트 제품 수량. */
	private int itemset_code_quantity;

	/** 상태. */
	private String itemset_code_condition;

	/** 등록일자. */
	private Date itemset_code_regdate;

	/** 세트 대표이미지. */
	private String itemset_code_mainimg;
	/**
	 * 생성자.
	 */
	public TbItemsetCodeVo() {
		
	}
	public TbItemsetCodeVo(int item_code_num, String itemset_code_category, String item_code_setname,
			int itemset_code_price, int itemset_code_quantity, String itemset_code_condition, Date itemset_code_regdate,
			String itemset_code_mainimg) {
		super();
		this.item_code_num = item_code_num;
		this.itemset_code_category = itemset_code_category;
		this.item_code_setname = item_code_setname;
		this.itemset_code_price = itemset_code_price;
		this.itemset_code_quantity = itemset_code_quantity;
		this.itemset_code_condition = itemset_code_condition;
		this.itemset_code_regdate = itemset_code_regdate;
		this.itemset_code_mainimg = itemset_code_mainimg;
	}
	public int getItem_code_num() {
		return item_code_num;
	}
	public void setItem_code_num(int item_code_num) {
		this.item_code_num = item_code_num;
	}
	public String getItemset_code_category() {
		return itemset_code_category;
	}
	public void setItemset_code_category(String itemset_code_category) {
		this.itemset_code_category = itemset_code_category;
	}
	public String getItem_code_setname() {
		return item_code_setname;
	}
	public void setItem_code_setname(String item_code_setname) {
		this.item_code_setname = item_code_setname;
	}
	public int getItemset_code_price() {
		return itemset_code_price;
	}
	public void setItemset_code_price(int itemset_code_price) {
		this.itemset_code_price = itemset_code_price;
	}
	public int getItemset_code_quantity() {
		return itemset_code_quantity;
	}
	public void setItemset_code_quantity(int itemset_code_quantity) {
		this.itemset_code_quantity = itemset_code_quantity;
	}
	public String getItemset_code_condition() {
		return itemset_code_condition;
	}
	public void setItemset_code_condition(String itemset_code_condition) {
		this.itemset_code_condition = itemset_code_condition;
	}
	public Date getItemset_code_regdate() {
		return itemset_code_regdate;
	}
	public void setItemset_code_regdate(Date itemset_code_regdate) {
		this.itemset_code_regdate = itemset_code_regdate;
	}
	public String getItemset_code_mainimg() {
		return itemset_code_mainimg;
	}
	public void setItemset_code_mainimg(String itemset_code_mainimg) {
		this.itemset_code_mainimg = itemset_code_mainimg;
	}
	
}