package net.stylesolo.www.vo;


/**
 * 세트 상품 이미지 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TbItemsetImgVo{
	/** 세트 상품 이미지 번호. */
	private int itemset_img_num;

	/** 추천 코드 테이블. */
	private int item_code_num;

	/** 세트 상품 이미지. */
	private String itemset_img_imgaddr;

	/**
	 * 생성자.
	 */
	public TbItemsetImgVo() {
	}

	public TbItemsetImgVo(int itemset_img_num, int item_code_num, String itemset_img_imgaddr) {
		super();
		this.itemset_img_num = itemset_img_num;
		this.item_code_num = item_code_num;
		this.itemset_img_imgaddr = itemset_img_imgaddr;
	}

	public int getItemset_img_num() {
		return itemset_img_num;
	}

	public void setItemset_img_num(int itemset_img_num) {
		this.itemset_img_num = itemset_img_num;
	}

	public int getItem_code_num() {
		return item_code_num;
	}

	public void setItem_code_num(int item_code_num) {
		this.item_code_num = item_code_num;
	}

	public String getItemset_img_imgaddr() {
		return itemset_img_imgaddr;
	}

	public void setItemset_img_imgaddr(String itemset_img_imgaddr) {
		this.itemset_img_imgaddr = itemset_img_imgaddr;
	}

}