package net.stylesolo.www.vo;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * È¸¿øÅ»ÅğÅ×ÀÌºí ¸ğµ¨ Å¬·¡½º.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class TbMemberOutVo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** È¸¿øÅ»Åğ¹øÈ£. */
	private Integer memberOutNum;

	/** È¸¿øÅ»Åğ»çÀ¯. */
	private String memberOutCause;

	/** È¸¿øÅ»Åğ½ÅÃ»ÀÏÀÚ. */
	private Date memberOutDate;

	/** È¸¿ø°¡ÀÔÅ×ÀÌºí. 
	private TbMemberPrivacyVo tbMemberPrivacy;
	*/
	
	public TbMemberOutVo() {}

	public TbMemberOutVo(Integer memberOutNum, String memberOutCause, Date memberOutDate,
			TbMemberPrivacyVo tbMemberPrivacy) {
		this.memberOutNum = memberOutNum;
		this.memberOutCause = memberOutCause;
		this.memberOutDate = memberOutDate;
//		this.tbMemberPrivacy = tbMemberPrivacy;
	}

	public Integer getMemberOutNum() {
		return memberOutNum;
	}

	public void setMemberOutNum(Integer memberOutNum) {
		this.memberOutNum = memberOutNum;
	}

	public String getMemberOutCause() {
		return memberOutCause;
	}

	public void setMemberOutCause(String memberOutCause) {
		this.memberOutCause = memberOutCause;
	}

	public Date getMemberOutDate() {
		return memberOutDate;
	}

	public void setMemberOutDate(Date memberOutDate) {
		this.memberOutDate = memberOutDate;
	}

	/*public TbMemberPrivacyVo getTbMemberPrivacy() {
		return tbMemberPrivacy;
	}

	public void setTbMemberPrivacy(TbMemberPrivacyVo tbMemberPrivacy) {
		this.tbMemberPrivacy = tbMemberPrivacy;
	}*/

	public static long getSerialversionuid() {
		return serialVersionUID;
	}


}
