package net.stylesolo.www.vo;
/*
	"SHOP_PAYMENT_ITEM_NUM" NUMBER(10,0) NOT NULL ENABLE, 
	"SHOP_PAYMENT_ITEM_ORDER_QTY" NUMBER(5,0) NOT NULL ENABLE, 
	"SHOP_PAYMENT_ITEM_PRICE" NUMBER(10,0) NOT NULL ENABLE, 
	"SHOP_PAYMENT_ORDERNUM" NUMBER(10,0) NOT NULL ENABLE, 
	"SHOP_ITEM_CODE" NUMBER(10,0), 
 */
public class TbShopPaymentProductVo {
	private int SHOP_PAYMENT_ITEM_NUM;
	private int SHOP_PAYMENT_ITEM_ORDER_QTY;
	private int SHOP_PAYMENT_ITEM_PRICE;
	private int SHOP_PAYMENT_ORDERNUM;
	private int SHOP_ITEM_CODE;
	private int ITEM_OPTIONS_NUM;
	
	public TbShopPaymentProductVo(){}

	public TbShopPaymentProductVo(int sHOP_PAYMENT_ITEM_NUM, int sHOP_PAYMENT_ITEM_ORDER_QTY,
			int sHOP_PAYMENT_ITEM_PRICE, int sHOP_PAYMENT_ORDERNUM, int sHOP_ITEM_CODE, int iTEM_OPTIONS_NUM) {
		super();
		SHOP_PAYMENT_ITEM_NUM = sHOP_PAYMENT_ITEM_NUM;
		SHOP_PAYMENT_ITEM_ORDER_QTY = sHOP_PAYMENT_ITEM_ORDER_QTY;
		SHOP_PAYMENT_ITEM_PRICE = sHOP_PAYMENT_ITEM_PRICE;
		SHOP_PAYMENT_ORDERNUM = sHOP_PAYMENT_ORDERNUM;
		SHOP_ITEM_CODE = sHOP_ITEM_CODE;
		ITEM_OPTIONS_NUM = iTEM_OPTIONS_NUM;
	}

	public int getITEM_OPTIONS_NUM() {
		return ITEM_OPTIONS_NUM;
	}

	public void setITEM_OPTIONS_NUM(int iTEM_OPTIONS_NUM) {
		ITEM_OPTIONS_NUM = iTEM_OPTIONS_NUM;
	}

	public int getSHOP_PAYMENT_ITEM_NUM() {
		return SHOP_PAYMENT_ITEM_NUM;
	}

	public void setSHOP_PAYMENT_ITEM_NUM(int sHOP_PAYMENT_ITEM_NUM) {
		SHOP_PAYMENT_ITEM_NUM = sHOP_PAYMENT_ITEM_NUM;
	}

	public int getSHOP_PAYMENT_ITEM_ORDER_QTY() {
		return SHOP_PAYMENT_ITEM_ORDER_QTY;
	}

	public void setSHOP_PAYMENT_ITEM_ORDER_QTY(int sHOP_PAYMENT_ITEM_ORDER_QTY) {
		SHOP_PAYMENT_ITEM_ORDER_QTY = sHOP_PAYMENT_ITEM_ORDER_QTY;
	}

	public int getSHOP_PAYMENT_ITEM_PRICE() {
		return SHOP_PAYMENT_ITEM_PRICE;
	}

	public void setSHOP_PAYMENT_ITEM_PRICE(int sHOP_PAYMENT_ITEM_PRICE) {
		SHOP_PAYMENT_ITEM_PRICE = sHOP_PAYMENT_ITEM_PRICE;
	}

	public int getSHOP_PAYMENT_ORDERNUM() {
		return SHOP_PAYMENT_ORDERNUM;
	}

	public void setSHOP_PAYMENT_ORDERNUM(int sHOP_PAYMENT_ORDERNUM) {
		SHOP_PAYMENT_ORDERNUM = sHOP_PAYMENT_ORDERNUM;
	}

	public int getSHOP_ITEM_CODE() {
		return SHOP_ITEM_CODE;
	}

	public void setSHOP_ITEM_CODE(int sHOP_ITEM_CODE) {
		SHOP_ITEM_CODE = sHOP_ITEM_CODE;
	}
	
}
