package net.stylesolo.www.vo;
/*
"SHOP_PAYMENT_ORDERNUM" NUMBER(10,0) NOT NULL ENABLE, 
"SHOP_PAYMENT_METHOD_PAYMENT" NUMBER(3,0) NOT NULL ENABLE, 
"SHOP_PAYMENT_COUPON" NUMBER(10,0) DEFAULT 0, 
"SHOP_PAYMENT_POINT" NUMBER(10,0) DEFAULT 0, 
"SHOP_PAYMENT_TOTAL_PRICE" NUMBER(10,0) NOT NULL ENABLE, 
"SHOP_PAYMENT_TOTAL_PAYMENT" NUMBER(10,0) NOT NULL ENABLE, 
"SHOP_PAYMENT_W_DATE" DATE NOT NULL ENABLE, 
"MEMBER_PRIVACY_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
 PRIMARY KEY ("SHOP_PAYMENT_ORDERNUM")
 */

import java.sql.Date;

public class TbShopPaymentVo {
	private int SHOP_PAYMENT_ORDERNUM;
	private int SHOP_PAYMENT_METHOD_PAYMENT;
	private int SHOP_PAYMENT_COUPON;
	private int SHOP_PAYMENT_POINT;
	private int SHOP_PAYMENT_TOTAL_PRICE;
	private int SHOP_PAYMENT_TOTAL_PAYMENT;
	private Date SHOP_PAYMENT_W_DATE;
	private String MEMBER_PRIVACY_ID;
	
	public TbShopPaymentVo(){}

	public TbShopPaymentVo(int sHOP_PAYMENT_ORDERNUM, int sHOP_PAYMENT_METHOD_PAYMENT, int sHOP_PAYMENT_COUPON,
			int sHOP_PAYMENT_POINT, int sHOP_PAYMENT_TOTAL_PRICE, int sHOP_PAYMENT_TOTAL_PAYMENT,
			Date sHOP_PAYMENT_W_DATE, String mEMBER_PRIVACY_ID) {
		super();
		SHOP_PAYMENT_ORDERNUM = sHOP_PAYMENT_ORDERNUM;
		SHOP_PAYMENT_METHOD_PAYMENT = sHOP_PAYMENT_METHOD_PAYMENT;
		SHOP_PAYMENT_COUPON = sHOP_PAYMENT_COUPON;
		SHOP_PAYMENT_POINT = sHOP_PAYMENT_POINT;
		SHOP_PAYMENT_TOTAL_PRICE = sHOP_PAYMENT_TOTAL_PRICE;
		SHOP_PAYMENT_TOTAL_PAYMENT = sHOP_PAYMENT_TOTAL_PAYMENT;
		SHOP_PAYMENT_W_DATE = sHOP_PAYMENT_W_DATE;
		MEMBER_PRIVACY_ID = mEMBER_PRIVACY_ID;
	}

	public int getSHOP_PAYMENT_ORDERNUM() {
		return SHOP_PAYMENT_ORDERNUM;
	}

	public void setSHOP_PAYMENT_ORDERNUM(int sHOP_PAYMENT_ORDERNUM) {
		SHOP_PAYMENT_ORDERNUM = sHOP_PAYMENT_ORDERNUM;
	}

	public int getSHOP_PAYMENT_METHOD_PAYMENT() {
		return SHOP_PAYMENT_METHOD_PAYMENT;
	}

	public void setSHOP_PAYMENT_METHOD_PAYMENT(int sHOP_PAYMENT_METHOD_PAYMENT) {
		SHOP_PAYMENT_METHOD_PAYMENT = sHOP_PAYMENT_METHOD_PAYMENT;
	}

	public int getSHOP_PAYMENT_COUPON() {
		return SHOP_PAYMENT_COUPON;
	}

	public void setSHOP_PAYMENT_COUPON(int sHOP_PAYMENT_COUPON) {
		SHOP_PAYMENT_COUPON = sHOP_PAYMENT_COUPON;
	}

	public int getSHOP_PAYMENT_POINT() {
		return SHOP_PAYMENT_POINT;
	}

	public void setSHOP_PAYMENT_POINT(int sHOP_PAYMENT_POINT) {
		SHOP_PAYMENT_POINT = sHOP_PAYMENT_POINT;
	}

	public int getSHOP_PAYMENT_TOTAL_PRICE() {
		return SHOP_PAYMENT_TOTAL_PRICE;
	}

	public void setSHOP_PAYMENT_TOTAL_PRICE(int sHOP_PAYMENT_TOTAL_PRICE) {
		SHOP_PAYMENT_TOTAL_PRICE = sHOP_PAYMENT_TOTAL_PRICE;
	}

	public int getSHOP_PAYMENT_TOTAL_PAYMENT() {
		return SHOP_PAYMENT_TOTAL_PAYMENT;
	}

	public void setSHOP_PAYMENT_TOTAL_PAYMENT(int sHOP_PAYMENT_TOTAL_PAYMENT) {
		SHOP_PAYMENT_TOTAL_PAYMENT = sHOP_PAYMENT_TOTAL_PAYMENT;
	}

	public Date getSHOP_PAYMENT_W_DATE() {
		return SHOP_PAYMENT_W_DATE;
	}

	public void setSHOP_PAYMENT_W_DATE(Date sHOP_PAYMENT_W_DATE) {
		SHOP_PAYMENT_W_DATE = sHOP_PAYMENT_W_DATE;
	}

	public String getMEMBER_PRIVACY_ID() {
		return MEMBER_PRIVACY_ID;
	}

	public void setMEMBER_PRIVACY_ID(String mEMBER_PRIVACY_ID) {
		MEMBER_PRIVACY_ID = mEMBER_PRIVACY_ID;
	}
	
}
