
/* Drop Triggers */

DROP TRIGGER TRI_TB_ADMIN_MEMBER_ADMIN_MEMBER_NUM;



/* Drop Tables */

DROP TABLE TB_ADMIN_MEMBER CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SEQ__ADMIN_MEMBER_NUM;




/* Create Sequences */

CREATE SEQUENCE SEQ_ADMIN_MEMBER_NUM INCREMENT BY 1 START WITH 1;



/* Create Tables */
CREATE TABLE TB_ADMIN_MEMBER
(
	ADMIN_MEMBER_NUM number(10,0) NOT NULL,
	ADMIN_MEMBER_CODE varchar2(20) UNIQUE,
	ADMIN_MEMBER_ID varchar2(50) NOT NULL UNIQUE,
	ADMIN_MEMBER_PASSWORD varchar2(50) NOT NULL,
	ADMIN_MEMBER_NAME varchar2(20) NOT NULL,
	ADMIN_MEMBER_BIRTH varchar2(20) NOT NULL,
	ADMIN_MEMBER_PHONE varchar2(30) NOT NULL,
	ADMIN_MEMBER_IP varchar2(40),
	ADMIN_MEMBER_EMAIL varchar2(50) UNIQUE,
	ADMIN_MEMBER_STATE varchar2(10),
	ADMIN_MEMBER_AUTHORITY varchar2(20),
	ADMIN_MEMBER_REGDATE date,
	PRIMARY KEY (ADMIN_MEMBER_NUM)
);



/* Create Triggers */

CREATE OR REPLACE TRIGGER TRI_TB_ADMIN_MEMBER_ADMIN_MEMBER_NUM BEFORE INSERT ON TB_ADMIN_MEMBER
FOR EACH ROW
BEGIN
	SELECT SEQ_TB_ADMIN_MEMBER_ADMIN_MEMBER_NUM.nextval
	INTO :new.ADMIN_MEMBER_NUM
	FROM dual;
END;

/




