
/* Drop Tables */

DROP TABLE TB_EVENTSALE_COMMENT CASCADE CONSTRAINTS;
DROP TABLE TB_EVENTSALE CASCADE CONSTRAINTS;
DROP TABLE TB_FAQ CASCADE CONSTRAINTS;
DROP TABLE TB_FBOARD_ATTRACTION_IMAGE CASCADE CONSTRAINTS;
DROP TABLE TB_FBOARD_ATTRACTION CASCADE CONSTRAINTS;
DROP TABLE TB_FBOARD_FESTIVAL_IMAGE CASCADE CONSTRAINTS;
DROP TABLE TB_FBOARD_FESTIVAL CASCADE CONSTRAINTS;
DROP TABLE TB_FBOARD_RESTAURANT_IMAGE CASCADE CONSTRAINTS;
DROP TABLE TB_FBOARD_RESTAURANT CASCADE CONSTRAINTS;
DROP TABLE TB_FBOARD_SHOPPING_IMAGE CASCADE CONSTRAINTS;
DROP TABLE TB_FBOARD_SHOPPING CASCADE CONSTRAINTS;
DROP TABLE TB_FBOARD CASCADE CONSTRAINTS;
DROP TABLE TB_FREE_COMMENT CASCADE CONSTRAINTS;
DROP TABLE TB_FREE_IMAGE CASCADE CONSTRAINTS;
DROP TABLE TB_FREE CASCADE CONSTRAINTS;
DROP TABLE TB_KBOARD CASCADE CONSTRAINTS;
DROP TABLE TB_LOGIN CASCADE CONSTRAINTS;
DROP TABLE TB_MARKET_COMMENT CASCADE CONSTRAINTS;
DROP TABLE TB_MARKET_IMAGE CASCADE CONSTRAINTS;
DROP TABLE TB_MARKET CASCADE CONSTRAINTS;
DROP TABLE TB_QNA CASCADE CONSTRAINTS;
DROP TABLE TB_REVIEW_COMMENT CASCADE CONSTRAINTS;
DROP TABLE TB_REVIEW_IMAGE CASCADE CONSTRAINTS;
DROP TABLE TB_REVIEW CASCADE CONSTRAINTS;
DROP TABLE TB_MEMBER CASCADE CONSTRAINTS;
DROP TABLE TB_NOTICE_COMMENTS CASCADE CONSTRAINTS;
DROP TABLE TB_NOTICE CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE TB_EVENTSALE
(
	EVENTSALE_NUM NUMBER(4) NOT NULL,
	CUSTOMER_NUM VARCHAR2(20) NOT NULL,
	EVENTSALE_SORT VARCHAR2(20),
	EVENTSALE_CATEGORY VARCHAR2(20),
	EVENTSALE_TITLE VARCHAR2(50),
	EVENTSALE_WRITER VARCHAR2(20),
	EVENTSALE_CONTENT VARCHAR2(3000),
	EVENTSALE_HIT NUMBER(5),
	EVENTSALE_W_DATE DATE,
	EVENTSALE_STARTDATE DATE,
	EVENTSALE_ENDDATE DATE,
	PRIMARY KEY (EVENTSALE_NUM)
);


CREATE TABLE TB_EVENTSALE_COMMENT
(
	EVENTSALE_COMMENT_NUM NUMBER(4) NOT NULL,
	EVENTSALE_NUM NUMBER(4) NOT NULL,
	EVENTSALE_COMMENT_WRITER VARCHAR2(20),
	EVENTSALE_COMMENT_CONTENT VARCHAR2(2000),
	EVENTSALE_COMMENT_W_DATE DATE,
	PRIMARY KEY (EVENTSALE_COMMENT_NUM)
);


CREATE TABLE TB_FAQ
(
	FAQ_NUM NUMBER(4) NOT NULL,
	FAQ_CATEGORY VARCHAR2(20) NOT NULL,
	FAQ_TITLE VARCHAR2(50) NOT NULL,
	FAQ_CONTENT VARCHAR2(3000),
	PRIMARY KEY (FAQ_NUM)
);


CREATE TABLE TB_FBOARD
(
	FBOARD_NUM NUMBER(4,0) NOT NULL,
	FBOARD_AREA VARCHAR2(30) NOT NULL,
	FBOARD_CITY VARCHAR2(30) NOT NULL,
	FBOARD_CATEGORY VARCHAR2(20),
	PRIMARY KEY (FBOARD_NUM)
);


CREATE TABLE TB_FBOARD_ATTRACTION
(
	FBOARD_ATTRACTION_NUM NUMBER(4,0) NOT NULL,
	FBOARD_NUM NUMBER(4,0) NOT NULL,
	FBOARD_ATTRACTION_TITLE VARCHAR2(100) NOT NULL,
	FBOARD_ATTRACTION_SUB_TITLE VARCHAR2(250),
	FBOARD_ATTRACTION_TIME VARCHAR2(500),
	FBOARD_ATTRACTION_PRICE VARCHAR2(300),
	FBOARD_ATTRACTION_HOME_PAGE VARCHAR2(200),
	FBOARD_ATTRACTION_GO VARCHAR2(1000),
	FBOARD_ATTRACTION_CONTENT VARCHAR2(3000),
	FBOARD_ATTRACTION_W_DATE DATE,
	PRIMARY KEY (FBOARD_ATTRACTION_NUM)
);


CREATE TABLE TB_FBOARD_ATTRACTION_IMAGE
(
	FBOARD_ATTRACTION_IMAGE_NUM NUMBER(4,0) NOT NULL,
	FBOARD_ATTRACTION_NUM NUMBER(4,0) NOT NULL,
	FBOARD_ATTRACTION_IMAGE_NAME VARCHAR2(70),
	PRIMARY KEY (FBOARD_ATTRACTION_IMAGE_NUM)
);


CREATE TABLE TB_FBOARD_FESTIVAL
(
	FBOARD_FESTIVAL_NUM NUMBER(4,0) NOT NULL,
	FBOARD_NUM NUMBER(4,0) NOT NULL,
	FBOARD_FESTIVAL_TITLE VARCHAR2(100) NOT NULL,
	FBOARD_FESTIVAL_SUB_TITLE VARCHAR2(250),
	FBOARD_FESTIVAL_PERIOD VARCHAR2(500),
	FBOARD_FESTIVAL_CONTENTS VARCHAR2(3000),
	FBOARD_FESTIVAL_W_DATE DATE,
	PRIMARY KEY (FBOARD_FESTIVAL_NUM)
);


CREATE TABLE TB_FBOARD_FESTIVAL_IMAGE
(
	FBOARD_FESTIVAL_IMAGE_NUM NUMBER(4,0) NOT NULL,
	FBOARD_FESTIVAL_NUM NUMBER(4,0) NOT NULL,
	FBOARD_FESTIVAL_IMAGE_NAME VARCHAR2(70),
	PRIMARY KEY (FBOARD_FESTIVAL_IMAGE_NUM)
);


CREATE TABLE TB_FBOARD_RESTAURANT
(
	FBOARD_RESTAURANT_NUM NUMBER(4,0) NOT NULL,
	FBOARD_NUM NUMBER(4,0) NOT NULL,
	FBOARD_RESTAURANT_TITLE VARCHAR2(100) NOT NULL,
	FBOARD_RESTAURANT_SUB_TITLE VARCHAR2(250),
	FBOARD_RESTAURANT_TIME VARCHAR2(500),
	FBOARD_RESTAURANT_PRICE VARCHAR2(300),
	FBOARD_RESTAURANT_HOME_PAGE VARCHAR2(200),
	FBOARD_RESTAURANT_GO VARCHAR2(1000),
	FBOARD_RESTAURANT_CONTENT VARCHAR2(3000),
	FBOARD_RESTAURANT_W_DATE DATE,
	PRIMARY KEY (FBOARD_RESTAURANT_NUM)
);


CREATE TABLE TB_FBOARD_RESTAURANT_IMAGE
(
	FBOARD_RESTAURANT_IMAGE_NUM NUMBER(4,0) NOT NULL,
	FBOARD_RESTAURANT_NUM NUMBER(4,0) NOT NULL,
	FBOARD_RESTAURANT_IMAGE VARCHAR2(70),
	PRIMARY KEY (FBOARD_RESTAURANT_IMAGE_NUM)
);


CREATE TABLE TB_FBOARD_SHOPPING
(
	FBOARD_SHOPPING_NUM NUMBER(4,0) NOT NULL,
	FBOARD_NUM NUMBER(4,0) NOT NULL,
	FBOARD_SHOPPING_TITLE VARCHAR2(100) NOT NULL,
	FBOARD_SHOPPING_SUB_TITLE VARCHAR2(250),
	TB_FBOARD_SHOPPING_TIME VARCHAR2(500),
	FBOARD_SHOPPING_HOME_PAGE VARCHAR2(200),
	FBOARD_SHOPPING_GO VARCHAR2(1000),
	FBOARD_SHOPPING_CONTENTS VARCHAR2(3000),
	FBOARD_SHOPPING_W_DATE DATE,
	PRIMARY KEY (FBOARD_SHOPPING_NUM)
);


CREATE TABLE TB_FBOARD_SHOPPING_IMAGE
(
	FBOARD_SHOPPING_IMAGE_NUM NUMBER(4,0) NOT NULL,
	FBOARD_SHOPPING_NUM NUMBER(4,0) NOT NULL,
	FBOARD_SHOPPING_IMAGE_NAME VARCHAR2(70),
	PRIMARY KEY (FBOARD_SHOPPING_IMAGE_NUM)
);


CREATE TABLE TB_FREE
(
	FREE_NUM NUMBER(4) NOT NULL,
	CUSTOMER_NUM VARCHAR2(20) NOT NULL,
	FREE_TITLE VARCHAR2(50) NOT NULL,
	FREE_CONTENT VARCHAR2(3000) NOT NULL,
	FREE_HIT NUMBER(5),
	FREE_W_DATE DATE,
	FREE_PASSWORD NUMBER(4) NOT NULL,
	FREE_WRITER VARCHAR2(30),
	PRIMARY KEY (FREE_NUM)
);


CREATE TABLE TB_FREE_COMMENT
(
	FREE_COMMENT_NUM NUMBER(4) NOT NULL,
	FREE_COMMENT_CONTENT VARCHAR2(2000) NOT NULL,
	FREE_COMMENT_W_DATE DATE,
	FREE_COMMENT_WRITER VARCHAR2(30),
	LEV NUMBER,
	STEP NUMBER,
	FREE_NUM NUMBER(4) NOT NULL,
	PRIMARY KEY (FREE_COMMENT_NUM)
);


CREATE TABLE TB_FREE_IMAGE
(
	FREE_IMAGE_NUM NUMBER(4) NOT NULL,
	FREE_IMAGE_ORIGINAL_NAME VARCHAR2(100),
	FREE_IMAGE_NAME VARCHAR2(100),
	FREE_NUM NUMBER(4) NOT NULL,
	PRIMARY KEY (FREE_IMAGE_NUM)
);


CREATE TABLE TB_KBOARD
(
	KBOARD_NUM NUMBER(4) NOT NULL,
	KBOARD_AREA VARCHAR2(30),
	KBOARD_CITY VARCHAR2(30),
	KBOARD_CATEGORY VARCHAR2(50),
	KBOARD_TITLE VARCHAR2(50),
	KBOARD_IMGNAME VARCHAR2(50),
	KBOARD_SAVE_IMGNAME VARCHAR2(50),
	KBOARD_CONTENT VARCHAR2(3000),
	KBOARD_PLUS_CONTENT VARCHAR2(2000),
	KBOARD_ADDR VARCHAR2(100),
	KBOARD_X VARCHAR2(100),
	KBOARD_Y VARCHAR2(100),
	PRIMARY KEY (KBOARD_NUM)
);


CREATE TABLE TB_LOGIN
(
	LOGIN_NUM NUMBER(4) NOT NULL,
	CUSTOMER_NUM VARCHAR2(20) NOT NULL,
	LOGIN_IP VARCHAR2(20),
	LOGIN_DATE DATE,
	PRIMARY KEY (LOGIN_NUM)
);


CREATE TABLE TB_MARKET
(
	MARKET_NUM NUMBER(4) NOT NULL,
	CUSTOMER_NUM VARCHAR2(20) NOT NULL,
	MARKET_SORT VARCHAR2(20) NOT NULL,
	MARKET_CATEGORY VARCHAR2(20) NOT NULL,
	MARKET_TITLE VARCHAR2(50) NOT NULL,
	MARKET_CONTENT VARCHAR2(3000),
	MARKET_PRICE NUMBER(10),
	MARKET_PHONE VARCHAR2(20),
	MARKET_HIT NUMBER(5),
	MARKET_W_DATE DATE,
	MARKET_WRITER VARCHAR2(20),
	PRIMARY KEY (MARKET_NUM)
);


CREATE TABLE TB_MARKET_COMMENT
(
	MARKET_COMMENT_NUM NUMBER(4) NOT NULL,
	MARKET_NUM NUMBER(4) NOT NULL,
	MARKET_COMMENT_WRITER VARCHAR2(20),
	MARKET_COMMENT_CONTENT VARCHAR2(2000),
	MARKET_COMMENT_W_DATE DATE,
	PRIMARY KEY (MARKET_COMMENT_NUM)
);


CREATE TABLE TB_MARKET_IMAGE
(
	MARKET_IMAGE_NUM NUMBER(4) NOT NULL,
	MARKET_NUM NUMBER(4) NOT NULL,
	MARKET_IMAGE_FILENAME VARCHAR2(100),
	MARKET_IMAGE_SAVEFILENAME VARCHAR2(100),
	PRIMARY KEY (MARKET_IMAGE_NUM)
);


CREATE TABLE TB_MEMBER
(
	MEMBER_NUM NUMBER(4) NOT NULL,
	CUSTOMER_NUM VARCHAR2(20) NOT NULL,
	LOGIN_ID VARCHAR2(15),
	MEMBER_PASSWORD VARCHAR2(15) NOT NULL,
	MEMBER_NICKNAME VARCHAR2(30),
	MEMBER_NAME VARCHAR2(15) NOT NULL,
	MEMBER_BIRTHDAY VARCHAR2(10) NOT NULL,
	MEMBER_PHONE NUMBER NOT NULL,
	MEMBER_EMAIL VARCHAR2(40) NOT NULL,
	MEMBER_POWER VARCHAR2(20),
	MEMBER_REGDATE DATE,
	PRIMARY KEY (CUSTOMER_NUM)
);


CREATE TABLE TB_NOTICE
(
	NOTICE_NUM NUMBER(4) NOT NULL,
	NOTICE_TITLE VARCHAR2(50),
	NOTICE_CONTENT VARCHAR2(3000),
	NOTICE_HIT NUMBER(5),
	NOTICE_W_DATE DATE,
	PRIMARY KEY (NOTICE_NUM)
);


CREATE TABLE TB_NOTICE_COMMENTS
(
	NOTICE_COMMENTS_NUM NUMBER(4) NOT NULL,
	NOTICE_NUM NUMBER(4) NOT NULL,
	NOTICE_COMMENTS_CONTENT VARCHAR2(2000),
	NOTICE_COMMENTS_W_DATE DATE,
	NOTICE_COMMENTS_WRITER VARCHAR2(50),
	PRIMARY KEY (NOTICE_COMMENTS_NUM)
);


CREATE TABLE TB_QNA
(
	QNA_NUM NUMBER(4) NOT NULL,
	CUSTOMER_NUM VARCHAR2(20) NOT NULL,
	QNA_STATE VARCHAR2(10),
	QNA_TITLE VARCHAR2(50),
	QNA_WRITER VARCHAR2(20),
	QNA_CONTENT VARCHAR2(3000),
	QNA_REPLY VARCHAR2(3000),
	QNA_HIT NUMBER(5),
	QNA_PASSWORD VARCHAR2(20),
	QNA_W_DATE DATE,
	PRIMARY KEY (QNA_NUM)
);


CREATE TABLE TB_REVIEW
(
	REVIEW_NUM NUMBER(4) NOT NULL,
	CUSTOMER_NUM VARCHAR2(20) NOT NULL,
	REVIEW_CATEGORY VARCHAR2(15),
	REVIEW_TITLE VARCHAR2(50) NOT NULL,
	REVIEW_CONTENT VARCHAR2(3000) NOT NULL,
	REVIEW_HIT NUMBER(5),
	REVIEW_W_DATE DATE,
	REVIEW_WRITER VARCHAR2(30),
	PRIMARY KEY (REVIEW_NUM)
);


CREATE TABLE TB_REVIEW_COMMENT
(
	REVIEW_COMMENT_NUM NUMBER NOT NULL,
	REVIEW_COMMENT_CONTENT VARCHAR2(2000) NOT NULL,
	REVIEW_COMMENT_W_DATE DATE,
	REVIEW_COMMENT_WRITER VARCHAR2(30),
	LEV NUMBER,
	STEP NUMBER,
	REVIEW_NUM NUMBER(4) NOT NULL,
	PRIMARY KEY (REVIEW_COMMENT_NUM)
);


CREATE TABLE TB_REVIEW_IMAGE
(
	REVIEW_IMAGE_NUM NUMBER(4) NOT NULL,
	REVIEW_IMAGE_ORIGINAL_NAME VARCHAR2(100),
	REVIEW_IMAGE_NAME VARCHAR2(100),
	REVIEW_NUM NUMBER(4) NOT NULL,
	PRIMARY KEY (REVIEW_IMAGE_NUM)
);



/* Create Foreign Keys */

ALTER TABLE TB_EVENTSALE_COMMENT
	ADD FOREIGN KEY (EVENTSALE_NUM)
	REFERENCES TB_EVENTSALE (EVENTSALE_NUM)
	ON DELETE CASCADE
;


ALTER TABLE TB_FBOARD_ATTRACTION
	ADD FOREIGN KEY (FBOARD_NUM)
	REFERENCES TB_FBOARD (FBOARD_NUM)
	ON DELETE CASCADE
;


ALTER TABLE TB_FBOARD_FESTIVAL
	ADD FOREIGN KEY (FBOARD_NUM)
	REFERENCES TB_FBOARD (FBOARD_NUM)
	ON DELETE CASCADE
;


ALTER TABLE TB_FBOARD_RESTAURANT
	ADD FOREIGN KEY (FBOARD_NUM)
	REFERENCES TB_FBOARD (FBOARD_NUM)
	ON DELETE CASCADE
;


ALTER TABLE TB_FBOARD_SHOPPING
	ADD FOREIGN KEY (FBOARD_NUM)
	REFERENCES TB_FBOARD (FBOARD_NUM)
	ON DELETE CASCADE
;


ALTER TABLE TB_FBOARD_ATTRACTION_IMAGE
	ADD FOREIGN KEY (FBOARD_ATTRACTION_NUM)
	REFERENCES TB_FBOARD_ATTRACTION (FBOARD_ATTRACTION_NUM)
	ON DELETE CASCADE
;


ALTER TABLE TB_FBOARD_FESTIVAL_IMAGE
	ADD FOREIGN KEY (FBOARD_FESTIVAL_NUM)
	REFERENCES TB_FBOARD_FESTIVAL (FBOARD_FESTIVAL_NUM)
	ON DELETE CASCADE
;


ALTER TABLE TB_FBOARD_RESTAURANT_IMAGE
	ADD FOREIGN KEY (FBOARD_RESTAURANT_NUM)
	REFERENCES TB_FBOARD_RESTAURANT (FBOARD_RESTAURANT_NUM)
	ON DELETE CASCADE
;


ALTER TABLE TB_FBOARD_SHOPPING_IMAGE
	ADD FOREIGN KEY (FBOARD_SHOPPING_NUM)
	REFERENCES TB_FBOARD_SHOPPING (FBOARD_SHOPPING_NUM)
	ON DELETE CASCADE
;


ALTER TABLE TB_FREE_COMMENT
	ADD FOREIGN KEY (FREE_NUM)
	REFERENCES TB_FREE (FREE_NUM)
	ON DELETE CASCADE
;


ALTER TABLE TB_FREE_IMAGE
	ADD FOREIGN KEY (FREE_NUM)
	REFERENCES TB_FREE (FREE_NUM)
	ON DELETE CASCADE
;


ALTER TABLE TB_MARKET_COMMENT
	ADD FOREIGN KEY (MARKET_NUM)
	REFERENCES TB_MARKET (MARKET_NUM)
	ON DELETE CASCADE
;


ALTER TABLE TB_MARKET_IMAGE
	ADD FOREIGN KEY (MARKET_NUM)
	REFERENCES TB_MARKET (MARKET_NUM)
	ON DELETE CASCADE
;


ALTER TABLE TB_EVENTSALE
	ADD FOREIGN KEY (CUSTOMER_NUM)
	REFERENCES TB_MEMBER (CUSTOMER_NUM)
;


ALTER TABLE TB_FREE
	ADD FOREIGN KEY (CUSTOMER_NUM)
	REFERENCES TB_MEMBER (CUSTOMER_NUM)
;


ALTER TABLE TB_LOGIN
	ADD FOREIGN KEY (CUSTOMER_NUM)
	REFERENCES TB_MEMBER (CUSTOMER_NUM)
;


ALTER TABLE TB_MARKET
	ADD FOREIGN KEY (CUSTOMER_NUM)
	REFERENCES TB_MEMBER (CUSTOMER_NUM)
;


ALTER TABLE TB_QNA
	ADD FOREIGN KEY (CUSTOMER_NUM)
	REFERENCES TB_MEMBER (CUSTOMER_NUM)
;


ALTER TABLE TB_REVIEW
	ADD FOREIGN KEY (CUSTOMER_NUM)
	REFERENCES TB_MEMBER (CUSTOMER_NUM)
;


ALTER TABLE TB_NOTICE_COMMENTS
	ADD FOREIGN KEY (NOTICE_NUM)
	REFERENCES TB_NOTICE (NOTICE_NUM)
	ON DELETE CASCADE
;


ALTER TABLE TB_REVIEW_COMMENT
	ADD FOREIGN KEY (REVIEW_NUM)
	REFERENCES TB_REVIEW (REVIEW_NUM)
	ON DELETE CASCADE
;


ALTER TABLE TB_REVIEW_IMAGE
	ADD FOREIGN KEY (REVIEW_NUM)
	REFERENCES TB_REVIEW (REVIEW_NUM)
	ON DELETE CASCADE
;




